/* Les textes de l'interface, en anglais et en français.
 *
 * L'interface s'ouvre en anglais ; un interrupteur du panneau la passe en
 * français (et retour) sans rien recharger.
 */
(function (racine) {
  "use strict";

  const TEXTES = {
      "en": {
          "nomExtension": "The Ping Show",
          "description": "Reads Discord out loud, live or as a replay, with a funny character voice for each person.",
          "titreAction": "Open The Ping Show",
          "commandeLecture": "Play / pause the reading",
          "lecture": "Play",
          "pause": "Pause",
          "lectureRaccourci": "Play / pause (Shift+Space)",
          "debut": "Start over from the oldest loaded message",
          "reculer": "Previous message (Shift+Left)",
          "suivant": "Next message (Shift+Right)",
          "arreter": "Stop",
          "direct": "Back to live",
          "transport": "Playback controls",
          "reglages": "Settings",
          "etatRepos": "Nothing is being read. Play starts live reading; the back arrow goes back one message.",
          "etatPreparation": "Preparing the voices…",
          "etatTelechargement": "Downloading the $1: $2% (one time only)",
          "voixAmericaines": "American voices",
          "voixBritanniques": "British voices",
          "voixFrancaises": "French voices",
          "etatDirect": "Live: $1",
          "etatDirectSimple": "Live: new messages are read as they arrive.",
          "etatRelecture": "Replay: message $1 of $2",
          "etatRattrapage": "Catching up: $1 new messages left, then live.",
          "etatReposNouveaux": "$1 new messages since the last reading. Play reads them, then goes live.",
          "etatReposUnNouveau": "1 new message since the last reading. Play reads it, then goes live.",
          "nouveaux": "$1 new messages",
          "unNouveau": "1 new message",
          "etatPause": "Paused on message $1 of $2.",
          "etatPauseSimple": "Paused.",
          "etatDebut": "This is the oldest loaded message. Discord loads more as you go up: try again in a moment.",
          "etatSansDiscord": "Open Discord in a tab of this browser (discord.com), then open a channel.",
          "etatSansMessages": "Discord is open, but I can't see any message. Open a channel or a thread.",
          "etatTrop": "Messages are coming too fast: skipping some to keep up.",
          "etatSonBloque": "Click anywhere in this panel to turn the sound on.",
          "etatErreur": "Problem: $1",
          "enAttente": "Waiting for the next message…",
          "troupe": "The characters on stage. Click one to hear it.",
          "volume": "Volume",
          "ambiance": "Background sound",
          "indicatifs": "Jingles",
          "indicatifsAide": "A one-second tune when a character takes the floor.",
          "tics": "Catchphrases",
          "ticsAide": "Lets each character add a few words of its own to what people wrote.",
          "emojis": "Emoji sounds",
          "emojisAide": "Each emoji plays a sound effect (applause, sad trombone, snoring…) or a word from the character.",
          "distribution": "Cast",
          "distributionVide": "Each person will appear here at their first message, with a voice from the pack above. You can change everything.",
          "redistribuer": "Draw again",
          "ecouter": "Hear this character",
          "nePasLire": "Don't read this person",
          "relire": "Read this person again",
          "personnageDe": "Character for $1",
          "voixMasculines": "Male voices",
          "voixFeminines": "Female voices",
          "genreH": "Male voice (click to change)",
          "genreF": "Female voice (click to change)",
          "genreInconnu": "Gender not guessed: voice drawn at random (click to choose)",
          "langue": "If unsure, read in",
          "langueAide": "Each message is read in English or French depending on its content. This decides when it is not clear.",
          "francais": "French",
          "anglais": "English",
          "raccourciLecture": "Play / pause",
          "raccourciPrecedent": "Previous message",
          "raccourciSuivant": "Next message",
          "confidentialite": "Voices are made in your browser. No message is sent anywhere.",
          "interface": "Language of this panel",
          "toucheMaj": "Shift",
          "toucheEspace": "Space",
          "avec": "with $1",
          "genre": "Guess gender",
          "genreAide": "Picks a male or a female voice from the first name. Off: any voice.",
          "paquet": "Voice pack",
          "tousLesPaquets": "All packs together",
          "ajouterPaquet": "Add a pack…",
          "retirerPaquet": "Remove this pack",
          "paquetAjoute": "Added: $1 ($2 voices).",
          "paquetAlertes": "Notes: $1.",
          "paquetRefuse": "Could not add “$1”: $2.",
          "paquetRetire": "Removed: $1.",
          "consigneOu": "In the Discord thread, anyone can type:",
          "consigneRefus": "To opt out and not be played:",
          "consigneRetour": "To opt in again:",
          "consigneChoix": "To select how you are played:",
          "consigneNom": "(name of voice)",
          "refus": "Asked not to be read (!voice off)",
          "sonChoix": "★ Their own pick: $1",
          "voixChoisie": "This person picked this voice themselves",
          "autrePaquet": "From another pack",
          "commandePrecedent": "Previous message",
          "commandeSuivant": "Next message",
          "raccourciChanger": "These keys work from any app. Change them at chrome://extensions/shortcuts. In this panel, Shift+Space and Shift+arrows work too."
      },
      "fr": {
          "nomExtension": "The Ping Show",
          "description": "Lit Discord à voix haute, en direct ou en relecture, avec une drôle de voix de personnage pour chaque interlocuteur.",
          "titreAction": "Ouvrir The Ping Show",
          "commandeLecture": "Lecture / pause",
          "lecture": "Lecture",
          "pause": "Pause",
          "lectureRaccourci": "Lecture / pause (Maj+Espace)",
          "debut": "Reprendre depuis le plus ancien message chargé",
          "reculer": "Message précédent (Maj+Gauche)",
          "suivant": "Message suivant (Maj+Droite)",
          "arreter": "Arrêter",
          "direct": "Revenir au direct",
          "transport": "Commandes de lecture",
          "reglages": "Réglages",
          "etatRepos": "Rien n'est lu pour l'instant. Lecture démarre le direct ; la flèche arrière remonte d'un message.",
          "etatPreparation": "Préparation des voix…",
          "etatTelechargement": "Téléchargement des $1 : $2 % (une seule fois)",
          "voixAmericaines": "voix américaines",
          "voixBritanniques": "voix britanniques",
          "voixFrancaises": "voix françaises",
          "etatDirect": "En direct : $1",
          "etatDirectSimple": "En direct : les nouveaux messages sont lus à leur arrivée.",
          "etatRelecture": "Relecture : message $1 sur $2",
          "etatRattrapage": "Rattrapage : encore $1 nouveaux messages, puis le direct.",
          "etatReposNouveaux": "$1 nouveaux messages depuis la dernière lecture. Lecture les lit, puis passe au direct.",
          "etatReposUnNouveau": "1 nouveau message depuis la dernière lecture. Lecture le lit, puis passe au direct.",
          "nouveaux": "$1 nouveaux messages",
          "unNouveau": "1 nouveau message",
          "etatPause": "En pause sur le message $1 sur $2.",
          "etatPauseSimple": "En pause.",
          "etatDebut": "C'est le plus ancien message chargé. Discord en charge d'autres quand on remonte : réessaie dans un instant.",
          "etatSansDiscord": "Ouvre Discord dans un onglet de ce navigateur (discord.com), puis affiche un salon.",
          "etatSansMessages": "Discord est ouvert, mais je ne vois aucun message. Affiche un salon ou un fil.",
          "etatTrop": "Ça va trop vite : je saute des messages pour rester à jour.",
          "etatSonBloque": "Clique n'importe où dans ce panneau pour activer le son.",
          "etatErreur": "Problème : $1",
          "enAttente": "En attente du prochain message…",
          "troupe": "Les personnages sur scène. Clique sur l'un d'eux pour l'entendre.",
          "volume": "Volume",
          "ambiance": "Fond sonore",
          "indicatifs": "Indicatifs",
          "indicatifsAide": "Un petit air d'une seconde quand un personnage prend la parole.",
          "tics": "Répliques",
          "ticsAide": "Chaque personnage ajoute quelques mots à lui à ce que les gens ont écrit.",
          "emojis": "Sons d'émojis",
          "emojisAide": "Chaque émoji joue un effet sonore (applaudissements, trombone triste, ronflement…) ou un mot du personnage.",
          "distribution": "Distribution",
          "distributionVide": "Chaque personne apparaîtra ici à son premier message, avec une voix du paquet ci-dessus. Tout reste modifiable.",
          "redistribuer": "Retirer au sort",
          "ecouter": "Écouter ce personnage",
          "nePasLire": "Ne pas lire cette personne",
          "relire": "Lire de nouveau cette personne",
          "personnageDe": "Personnage de $1",
          "voixMasculines": "Voix masculines",
          "voixFeminines": "Voix féminines",
          "genreH": "Voix masculine (clique pour changer)",
          "genreF": "Voix féminine (clique pour changer)",
          "genreInconnu": "Genre non deviné : voix tirée au sort (clique pour choisir)",
          "interface": "Langue de ce panneau",
          "langue": "Dans le doute, lire en",
          "langueAide": "Chaque message est lu en anglais ou en français selon son contenu. Ce réglage tranche quand ce n'est pas clair.",
          "francais": "Français",
          "anglais": "Anglais",
          "raccourciLecture": "Lecture / pause",
          "raccourciPrecedent": "Message précédent",
          "raccourciSuivant": "Message suivant",
          "confidentialite": "Les voix sont fabriquées dans ton navigateur. Aucun message n'est envoyé.",
          "toucheMaj": "Maj",
          "toucheEspace": "Espace",
          "avec": "avec $1",
          "genre": "Deviner le genre",
          "genreAide": "Choisit une voix d'homme ou de femme d'après le prénom. Éteint : n'importe quelle voix.",
          "paquet": "Paquet de voix",
          "tousLesPaquets": "Tous les paquets ensemble",
          "ajouterPaquet": "Ajouter un paquet…",
          "retirerPaquet": "Retirer ce paquet",
          "paquetAjoute": "Ajouté : $1 ($2 voix).",
          "paquetAlertes": "Remarques : $1.",
          "paquetRefuse": "Impossible d'ajouter « $1 » : $2.",
          "paquetRetire": "Retiré : $1.",
          "consigneOu": "Dans le fil Discord, chacun peut écrire :",
          "consigneRefus": "Pour ne pas être lu :",
          "consigneRetour": "Pour être lu de nouveau :",
          "consigneChoix": "Pour choisir sa voix :",
          "consigneNom": "(nom de la voix)",
          "refus": "A demandé à ne pas être lu (!voice off)",
          "sonChoix": "★ Son propre choix : $1",
          "voixChoisie": "Cette personne a choisi cette voix elle-même",
          "autrePaquet": "D'un autre paquet",
          "commandePrecedent": "Message précédent",
          "commandeSuivant": "Message suivant",
          "raccourciChanger": "Ces touches marchent depuis n'importe quelle application. Pour les changer : chrome://extensions/shortcuts. Dans ce panneau, Maj+Espace et Maj+flèches marchent aussi."
      }
  };

  let langue = "en";
  function choisir(code) { langue = TEXTES[code] ? code : "en"; return langue; }
  // Le texte d'une clé dans la langue de l'interface ; $1, $2… sont remplacés par les valeurs.
  function dire(cle, ...valeurs) {
    const modele = TEXTES[langue][cle] ?? TEXTES.en[cle] ?? cle;
    return modele.replace(/\$(\d)/g, (_, n) => String(valeurs[Number(n) - 1] ?? ""));
  }

  const api = { TEXTES, dire, choisir, langue: () => langue };
  racine.PingTextes = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof self !== "undefined" ? self : globalThis);
